# Generated by Django 3.1.1 on 2020-09-06 14:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_processing', '0004_auto_20200906_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='percentage_compression',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
